spring.application.name=cvraterai

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.jpa.properties.hibernate.default_schema=cvraterai
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Scheduler ayarları
spring.task.scheduling.pool.size=5
spring.task.execution.pool.max-size=10

# Loglama seviyelerini ayarla
logging.level.root=INFO
logging.level.com.birkann=DEBUG
logging.level.com.birkann.service.impl.UserService=DEBUG
logging.level.com.birkann.controller.CVEvaluationController=DEBUG
logging.level.com.birkann.jwt.JWTAuthenticaterFilter=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.com.birkann.oauth2=DEBUG

# Log formatını düzenle
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Performans ayarları
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# Dosya yükleme ayarları
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload.dir=./uploads

# Gemini API ayarları
gemini.api.key=AIzaSyDyUAJK7t3bJ72YbLrHjrCgyD1v99ijTZQ
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

# GitHub API Configuration
github.api.token=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

# JWT ayarları
jwt.refreshExpirationDateInMs=604800000

# Timeout ayarları
spring.mvc.async.request-timeout=180000
server.tomcat.connection-timeout=180000
server.tomcat.max-threads=200
server.tomcat.min-spare-threads=20
server.connection-timeout=180000
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# OAuth2 Client Configuration
spring.security.oauth2.client.registration.google.client-id=86639053750-cn8feuf70v6h3folq24lu28u1s9d065j.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile,openid,https://www.googleapis.com/auth/gmail.readonly
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/oauth2/callback/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# OAuth2 App Configuration
app.oauth2.redirectUri=http://localhost:8080/oauth2/callback/google
app.oauth2.authorizedRedirectUri=http://localhost:8080/oauth2/callback/google

# Frontend yönlendirme URI'si
oauth2.redirectUri=http://localhost:3000/oauth/callback